export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGOUT = "LOGOUT";
export const FETCH_CUSTOMERS = "FETCH_CUSTOMERS";

export const DELETE_CUSTOMER = "DELETE_CUSTOMER";

export const EDIT_CUSTOMER = "EDIT_CUSTOMER";

export const ADD_CUSTOMER = "ADD_CUSTOMER";
